[package]
name = "bubshurb/cmdr"
description = "Cmdr fork"
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs"]
include = ["CHANGELOG.md", "Cmdr", "default.project.json", "LICENSE"]

[dependencies]